version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: localhost
    ports:
      - "27017:27017"
    volumes:
     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#      - ./mongodb-data:/data/db/
    #      - ./mongodb-log:/var/log/mongodb/
    command: ["mongod", "--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: library
      MONGO_INITDB_ROOT_PASSWORD: library

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    #restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: library
      ME_CONFIG_MONGODB_ADMINPASSWORD: library
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_BASICAUTH_USERNAME: library
      ME_CONFIG_BASICAUTH_PASSWORD: library
      ME_CONFIG_MONGODB_URL: mongodb://library:library@mongo:27017/library?authSource=admin
    ports:
      - 8081:8081
    depends_on:
      - mongodb
